# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0002_auto_20170320_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
