# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0005_auto_20170321_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='quesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_paper_id', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_paper_id', models.CharField(max_length=50)),
                ('questionNo', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=500, unique=True)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=500)),
                ('questionType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='studentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_paper_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('marks', models.CharField(max_length=50)),
            ],
        ),
    ]
