# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0008_auto_20170321_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='institutionID',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institute',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
