# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0009_auto_20170321_1541'),
        ('onlinetest', '0007_auto_20170321_0919'),
    ]

    operations = [
    ]
